name: 1461 Day's of Trump
description: Day by day of Trumps time in office
author: DaysOfTrump Team
category_dir: /
url: https://daysoftrump.github.io/
markdown: kramdown 
permalink: pretty
paginate: 8
exclude: [README.md]
